name = "samuapi"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SAMU_KV"
id = "464efbe9e56a4c24bb2005d1d1d28ad4"

[vars]
# API_SECRET est une variable secrète, à définir via :
# wrangler secret put API_SECRET
